# This is a basic workflow to help you get started with Actions

name: Upload

on:
  push:
    branches:
    - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    env:
      AWS_REGION: eu-north-1
    steps:
        - run: ls
        - run: pwd
        - run: aws s3 cp "Aris portfolio/index.html" "s3://www.aristeidiseleftheriou.com/Aris portfolio/"
