# This is a basic workflow to help you get started with Actions

name: CI

on:

  pull_request:
    branches: [ "main" ]



jobs:
 
  build:

    runs-on: ubuntu-18.04

    steps:
 
      - uses: actions/checkout@v3
        with:
          aws_key_id: ${{ secrets.AWS_KEY_ID }}
          aws_secret_access_key: ${{ secrets.AWS_SECRET_ACCESS_KEY}}
          aws_bucket: ${{ secrets.AWS_BUCKET }}
          aws-region: eu-north-1
      - run: aws s3 sync ./out s3://www.aristeidiseleftheriou.com/Aris portfolio/



